### ISSUE TITLE
Use the new allergens.json file to translate allergens

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#1025]
https://static.openfoodfacts.org/data/taxonomies/allergens.json
```
{  
   "en:lupin":{  
      "name":{  
         "es":"Altramuces",
         "ar":"ترمس",
         "cs":"Vlčí bob",
         "bg":"Лупина",
         "nl":"Lupine",
         "et":"Lupiin",
         "de":"Lupinen",
         "fi":"Lupiinit",
         "hu":"Csillagfürt",
         "en":"Lupin",
         "el":"Λούπινο",
         "ga":"Lúipín",
         "pl":"Łubin",
         "sv":"Lupin",
         "lt":"Lubinai",
         "mt":"Lupina",
         "it":"Lupini",
         "th":"ลูพิน",
         "fr":"Lupin",
         "sk":"Vlčí bôb",
         "jp":"ルピナス属",
         "ro":"Lupin",
         "lv":"Lupīna",
         "da":"Lupin",
         "sl":"Volčji",
         "pt":"Tremoço",
         "zh":"羽扇豆"
      }
   }

```

**Comment by Shubham2320** [comment]
I am working on this one along with #943 both are same.

**Comment by Shubham2320** [comment]
The response of the given link doesn't contain translations of all allergens present in the English language. So what is supposed to be done, is it the case that right now it just has to be implemented and in future other translations would also be made available in the same link?

**Comment by teolemon** [comment]
The link contains the official list of allergenic substances and their translations in many langages. The previous list has user imputed allergens that are not translated nor linked (eg mozzarella).

So we were giving false expectations the feature would work properly.

We'll stick to that shorter list, and make it evolve as we translate it, and expand it beyond allergens ( for people who don't like broccoli)

Future updates will be available at that URL, and that's why I've also opened an issue for the update mechanism

**Comment by Shubham2320** [comment]
Now, after a lot of analysis of the whole code, I found that the link which we're using now has 2,356 allergens this number include the repetition of single allergen in different languages.

The structure of this allergen contains name, URL and number of products.
So in order to use the new link, we would be losing the number of products and URL which in my opinion is also not much necessary.

**Now I've thought an approach:**

Structure of `allergen` would contain: 

1. `id` =  id of allergen: which will be always in English for example "en:milk"
2. `name` = name of allergen in the local language(Chosen language)
3. `translation` A JSON object which would contain the translation of this allergen in other languages.

Approach:

At firstRun we would get the response from the server and store it in greenDao DB which would contain the ArrayList of described `allergen` structure.

Now, whenever the user will choose a different language we would run a loop for all elements of allergens ArrayList and store the translation in `name` from `translation`, then this ArrayList would be updated in DB.

I'll make sure that no other functionality gets affected by these changes.
Please provide your thoughts @teolemon  :).
