### ISSUE TITLE
Memory issues after Search

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#1039]
**Summary:** 

After doing a search, and scrolling a lot, the app becomes slower and unresponsive

**Steps to reproduce:** 
Search for coca, click on the first product. It loads quite fast.
Search for coca, scroll a lot to the bottom, go back to the first product. Click on it, it loads slower.
Scroll even more, do even more searches, eventually the app stops responding.

**Expected behavior:** 

Stay fast

**Comment by samagra14** [comment]
I would love to take a sneek into the memory issues.

**Comment by Karljoones** [comment]
@samagra14 are you working on this?

**Comment by samagra14** [comment]
@Karljoones There was no mutual consent on how to solve this. The discussion can be seen in #995 .

**Comment by Karljoones** [comment]
@samagra14 the list should be put into a recylerview, this is the most efficient list view at the moment in Android. You should not save this information in a savedInstanceBundle as this is not what it is used for, the only thing that should be saved there is the search query, not the array that the list is displaying. The activity should be handled by the life cycle rather than telling the app not to kill the activity, telling Android not to kill the activity is bad practise.

**Comment by teolemon** [comment]
hopefully solved with the refactoring @Karljoones @samagra14 
by the way, help to restabilize the app welcome 🙂
