### ISSUE TITLE
No translations + Duplicate additives

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#1231]
![image](https://user-images.githubusercontent.com/1689815/37336646-552ff860-26b2-11e8-8ef0-f11a8dac80dd.png)

- The translation don't appear (fresh install, the translation file wasn't there yet, possibly)
- The additives appear duplicated.
- Erratic carriage return

**Comment by shivanshsoni** [comment]
I am taking this issue

**Comment by l-o-b-s-t-e-r** [comment]
@teolemon 
What is the product on the screenshot?
As I told earlier, the size of JSONs are huge, it takes ~4 minutes to save all translations to local database.

**Comment by l-o-b-s-t-e-r** [comment]
@teolemon 
To tell the truth the list of Additives looks pretty strange. What is this version?

**Comment by l-o-b-s-t-e-r** [comment]
@teolemon 
ping

**Comment by teolemon** [comment]
It is latest trunk, with app cache wiped, and this product: https://world.openfoodfacts.org/product/7622210125439/napolitain-chocolat-framboise-lu

(though the bug happens with shorter additives list as well)

**Comment by l-o-b-s-t-e-r** [comment]
@teolemon 
Duplicated additives - it's easy to fix, already fixed.
Translations - it takes really long time to save everything to the local database. Probably, you didn't see translations, because they were being saved at that moment...

After clearing the cache, the local database was deleted, so the data had to been loaded and saved again.
