### ISSUE TITLE
Better photo flow for power users

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/OpenFoodFacts-androidApp#124]
Power contributors want to quicky scan products in a supermarket to see which one are not in the database.
A power mode where the barcode scanner : 
- would keep scanning if the product is present 
- just overlay for 5 sec a green tick and the date of the most recent photo (if the product is present)
- overlay a button to take photos (with the same viewfinder) that would automatically be added to the last scanned product  (in any case)

**Comment by itchix** [comment]
![image](https://cloud.githubusercontent.com/assets/2846894/21743308/d416355a-d4ff-11e6-9bfd-063bdd69ecaf.png)

You can zoom the image.
If the product does not exist the flow is the same as usual.

**Comment by teolemon** [comment]
Mmh, it redirects on the product page. Has never worked for me. What am I doing wrong ?

**Comment by itchix** [comment]
I've just implemented it today =)

**Comment by teolemon** [comment]
would it be possible to add the name, brand, weight and nutriscore ?

**Comment by itchix** [comment]
Yes

**Comment by itchix** [comment]
And like that ?

**Comment by teolemon** [comment]
GitHub has eaten the screenshot :-)

**Comment by itchix** [comment]
![image](https://cloud.githubusercontent.com/assets/2846894/21743568/e55a1a0c-d504-11e6-834e-9adabf81f37d.png)

**Comment by teolemon** [comment]
sweet :-)

**Comment by itchix** [comment]
see 90eeb63ee3ff49f907da39ba70d2e5862a2104cc

**Comment by herau** [comment]
i'm not a big fan of this UX for many reasons:

- The title of the dialog should be the name of the product or a more explicit title than `power mode`
- the message `the product you scanned does already exist in open food facts` does not give any information for the user. it's obvious that the product exist because we print this dialog (otherwise you ask to the user to add it on OFF).
- i don't like the grey background with the 5C image with a white background -- why not a white background in the all dialog ?
- Currently we are trying to apply the Material design concepts and i think this dialog doesn't take care of it https://material.io/guidelines/components/dialogs.html#dialogs-specs

**Comment by teolemon** [comment]
After thinking about it, we could display the info at the bottom of the screen, in a edge to edge card, that you could swipe up to get more info ?

**Comment by teolemon** [comment]
![image](https://cloud.githubusercontent.com/assets/1689815/21745447/9aa375e4-d52c-11e6-906a-84e8af2a6415.png)

**Comment by teolemon** [comment]
V1 for reference:
![image](https://cloud.githubusercontent.com/assets/1689815/21745450/c9c81e74-d52c-11e6-987a-209e1084b98a.png)

**Comment by teolemon** [comment]
![image](https://cloud.githubusercontent.com/assets/1689815/21745468/604b286e-d52d-11e6-9fba-8e2f675f283c.png)

**Comment by teolemon** [comment]
![image](https://cloud.githubusercontent.com/assets/1689815/21745561/efd9096e-d52e-11e6-9026-ef4a6c17eeb2.png)
Idea stolen from Google Maps

**Comment by herau** [comment]
@teolemon your screenshot is better than the current version
@itchix the code from 90eeb63 added a lot a complexity in the method. maybe extract your code in another class ?

I think this feature should have given rise to the opening of a MR instead of pushed in the master branch; to discuss about the feature before merge of the code in the master branch

**Comment by teolemon** [comment]
![image](https://cloud.githubusercontent.com/assets/1689815/21745647/677835b6-d530-11e6-9d88-861df6e8645b.png)
Here's what could happen if the product does not exist.

**Comment by herau** [comment]
@teolemon should be in another issue ? i like your idea anyway. maybe `barecode will automatically scan` message is quite useless.

**Comment by teolemon** [comment]
it's from an iOS screenshot I got on the web :-D

**Comment by teolemon** [comment]
This is what could happen if the product is uncomplete

![image](https://cloud.githubusercontent.com/assets/1689815/21966003/4175660e-db6b-11e6-9ac2-6b2fdeefe281.png)
