### ISSUE TITLE
Many Travis build are failing, exceeding the time limit

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#1256]
Many Travis build are failing, exceeding the time limit.

**Comment by huzaifaiftikhar** [comment]
#1115  is the latest merge where we changed the travis configuration.

**Comment by geekanamika** [comment]
@huzaifaiftikhar Travis file currently contains `./gradlew assembleDebug --stacktrace' in *install*  which should not be required. `./gradlew build connectedCheck --stacktrace` is enough for building the project. 
Also, it should be configured to cache the results to speed up the travis build process. 
I can fix it if this is approved. #1275 also fails due to exceeding time limit & it must be fixed.

**Comment by huzaifaiftikhar** [comment]
After doing quite a lot of study on Travis I found out that : 
- `./gradlew assembleDebug --stacktrace` command is actually not required, this builds the Debug version of the app. Since we are already building all the flavors of the app by `./gradlew build connectedCheck --stacktrace` which runs both the assemble and check task therefore the building of debug is not at all required and this line can be removed.
- Also the command  `./gradlew assembleDebug --stacktrace` takes up to 320-350 seconds to execute which is approximately equal to 5-6 mins. This can be minimized by removing this line.
- Also, we have used _cache directories_ but have not cached it properly I guess and missed a **"."** I think it should be like this `${TRAVIS_BUILD_DIR}/.gradle/caches/` and `${TRAVIS_BUILD_DIR}/.gradle/wrapper/dists/`. We can also add `${TRAVIS_BUILD_DIR}/.android/build-cache` for android build cache.
- Another command which takes a lot of time is `android-wait-for-emulator`. This also takes up to 5-6 mins for execution. Do we have tests (Instrumentation) that require an emulator? Or can we simply configure Travis without an emulator. @l-o-b-s-t-e-r , I need your opinion on this point.
