### ISSUE TITLE
username disappears if the password is wrong

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#1486]
When trying to login, username disappears if the password is wrong

Expected: the username should stay, only the password should disappear

**Comment by PrajwalM2212** [comment]
@teolemon  The login fails either if password or username or both are wrong . But it is not possible to determine whether it failed due to incorrect name or password or both . 
We could let the username persist if we knew that the login failed due to incorrect password , but now it is not possible to do so.

**Comment by teolemon** [comment]
We need a serverside update theoretically, but I think we could leave the username anyway.
The user will be easily able to see if he/she has done a typo.

**Comment by cliffgr** [comment]
Seems this issue is fixed .. we can close it

**Comment by PrajwalM2212** [comment]
Thanks @cliffgr .
