### ISSUE TITLE
Scan on Shake in preferences makes the app go back to homescreen

### ISSUE THREAD

**Issue by huzaifaiftikhar** [openfoodfacts/openfoodfacts-androidapp#1500]
**Checklist**
- [x] Bug Report - The issue you are reporting might be there already. Please search on the [issues tracker](https://github.com/openfoodfacts/openfoodfacts-androidapp/issues) before creating or reporting an issue.
- [x] Before reporting, please ensure (if you can) that you have tested it with the latest (dev) version of the software.
- [x] Don't forget to tag your issue, it makes it easier to discover.

**Summary:** 
Clicking the checkbox of _Scan on Shake_ in _Preferences_ navigates the user back to the home screen. The checkbox should function like other checkboxes (_Scan on startup_ and _Power mode scan_).

**Steps to reproduce:** 
Open Preferences from the Navigation Drawer. Click on _Scan on Shake_.

**Expected behavior:** 
The Scan on Shake checkbox should get checked/unchecked depending upon its previous value.

**Observed behavior:** 
Navigated back to Home Screen.

**Comment by etcadinfinitum** [comment]
@Karljoones @teolemon @huzaifaiftikhar 
 
in ```MainActivity.java```, there is this overridden method:
```
    @Override
    public void onSharedPreferenceChanged(SharedPreferences sharedPreferences, String s) {

        // restart activity if scan on shake is chosen
        if (sharedPreferences.getBoolean("shakeScanMode", false) != scanOnShake) {
            this.recreate();
        }

    }
```
I assume that the method was added for a specific reason at some point in time, but I am not sure if it is still needed, since it's sole purpose is to produce the undesired behavior seen here as far as I can tell... 
There are calls to handle the preferences changed listener registration/removal in ```onResume()``` and ```onPause()```. 

I am submitting a PR for this issue; I refactored some of the ```onCreate()``` code into a new method (```setShakePreferences()```), and simply call the new method from ```onCreate``` and ```onSharedPreferenceChanged```. The method avoids duplicating the lines which: A) assign the ```shakePreference.getBoolean``` value to the ```scanOnShake``` variable, and B) create the ```ShakeListener``` object. (I left the shakeListener as an anonymous listener; I assume this was a design choice.) If you would rather see a different implementation, let me know.
