### ISSUE TITLE
Refresh taxonomies only is the only file has changed

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#1616]
- We currently refresh every 24 hours:
https://github.com/openfoodfacts/openfoodfacts-androidapp/blob/585b4561869360c73b22cc4b95edcb1e69628284/app/src/main/java/openfoodfacts/github/scrachx/openfood/views/splash/SplashPresenter.java#L22
- We should only refresh if 'If-Modified-Since" is sent back
https://android.jlelse.eu/reducing-your-networking-footprint-with-okhttp-etags-and-if-modified-since-b598b8dd81a1
- Clarify the loading screen. During taxonomy loading, display "Initialisation" instead of "Loading"

**Comment by prashantkh19** [comment]
@teolemon I would like to work on it..

**Comment by teolemon** [comment]
You can go ahead. A couple of precisions:
- I modified the time to be more or less 6 months, but that's not ideal at all
- The last point has been fixed (the loading screen is ok, we could make it granular by telling "Loading ingredients, loading additives…)
- The really big pain point is to reload on 'If-Modified-Since'

(Eventually, I'd like background download to avoid waiting too much on first use.)

**Comment by prashantkh19** [comment]
@teolemon I tried using `304 NOT MODIFIED status`, i.e every time when the app opens, I will make a server call, and if the server responds with `304 NOT MODIFIED status`, I am not saving the data. But making call to the server for checking the status itself takes considerable time (just saving time to the database is reduced). So, doing this everytime the app opens won't be a good idea.
One better approach would be to use a refresh-period(~6-7 days) on top of `If-Modified-Since` approach.
What do you think?

**Comment by deniger** [comment]
should be changed now as we can check the last modified date

**Comment by teolemon** [comment]
@deniger I'm assuming it's fixed now. Closing
