### ISSUE TITLE
Shake to scan seems broken

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#1799]
Shake to scan seems broken
Open Pet Food Facts, latest version

**Comment by ivanhercaz** [comment]
Hi @teolemon,

I was experimenting today with Open Food Facts. I enabled the shake option but I got an important bug: when this option is enabled it enters automatically in the scan mode and I can't exit, if I press the back button of my smartphone the app enters again in loop.

I thought "maybe if I close the app and enter again", but not, this didn't work, because the app enter again in the scan mode. It is very strange, because I didn't shake the mobile, and it happens when I have it above a table too.

I have to test it in another smartphones, but I got this error in a Moto X Play with Android 7.1.1.

I don't know if this is related with this issue, due you specified "Open Pet Food Facts, latest version", but I prefer to comment it here to avoid duplicated issues. If you consider it could be another issue, tell me and I will report it with images or even a video-gif of what happened to me.

I await your answer!
