### ISSUE TITLE
Encoding error on the Product URL field search function

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#1864]
Encoding error on the search function within the Product URL field in the edit mode

![image](https://user-images.githubusercontent.com/1689815/44789039-e2506400-ab9b-11e8-82a8-1a9adbc9e8f6.png)

**Comment by teolemon** [comment]
Generate the above barcode, using: https://barcode.tec-it.com/en/EAN13
Go into edit mode, on the first page, expand all the section, and look for the magnifier glass icon and click on it.

**Comment by jaindiv26** [comment]
@teolemon @brandenfung It's not an encoding error, the search field is properly doing what it should do. The search URL consists of a barcode, the brand name, product name along with the text "OFFICIAL WEBSITE". It would somewhat look like this (url = code + brand.getText + name.getText + "OFFICIAL WEBSITE"). I've tested this search field and it works just fine for the other products. 

The google search text in the above-mentioned screenshot is not an encoding error. Before the API call it would look like this, (url = https://www.google.com/search?q=3256220661249  U  Mélange fruits du verger et graines grillées). Where u is brand name, and product name is Mélange fruits du verger et graines grillées.

So that's not an encoding error, it's just the product name that looks messy when it's searched on google.

![screenshot_1536300693](https://user-images.githubusercontent.com/32436867/45202069-4f977f80-b295-11e8-9485-485ae897f585.png)

![screen shot 2018-09-07 at 11 47 52 am](https://user-images.githubusercontent.com/32436867/45202089-69d15d80-b295-11e8-984e-c453d4cc43c7.png)
