### ISSUE TITLE
Wikipedia Going further has only placeholders

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#1865]
Not sure how I reached this. Probably unfixable right now, and low impact

![image](https://user-images.githubusercontent.com/1689815/44789217-4f63f980-ab9c-11e8-811d-1ad5b2f701c8.png)

**Comment by jaindiv26** [comment]
@teolemon I think it may happen due to slow internet connectivity or dead link mentioned Labels, Marques, etc. I've reproduced this issue but all seems to work just fine.

![screenshot_1536247734](https://user-images.githubusercontent.com/32436867/45168084-1d940800-b218-11e8-9e2e-03f692686951.png)

![screenshot_1536247775](https://user-images.githubusercontent.com/32436867/45168104-2ab0f700-b218-11e8-8b62-719be3efc0b0.png)
