### ISSUE TITLE
Country where sold not in proper english

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#252]
en:FR

![screenshot_20161115-130456](https://cloud.githubusercontent.com/assets/1689815/20306409/56f720a0-ab3a-11e6-8cab-fe1e221d82b9.png)

**Comment by teolemon** [comment]
After the Scanbot edits, this problem is even more visible on many products.

**Comment by teolemon** [comment]
![image](https://cloud.githubusercontent.com/assets/1689815/20833412/dc4a330c-b88f-11e6-8703-e1ecf1be6780.png)

**Comment by teolemon** [comment]
http://fr.openfoodfacts.org/pays.json
http://world.openfoodfacts.org/countries.json

**Comment by teolemon** [comment]
@herau @itchix To solve this, we have to download the countries list JSON for the current language, and get the ```name``` parameter.

http://fr.openfoodfacts.org/pays.json
```{"products":21,"name":"Autriche","id":"en:austria","url":"https://fr.openfoodfacts.org/pays/autriche"},```

http://world.openfoodfacts.org/countries.json
```{"url":"https://world.openfoodfacts.org/country/austria","id":"en:austria","name":"Austria","products":400},```

**Comment by huzaifaiftikhar** [comment]
@teolemon I guess this issue is now fixed and we can close this. This can be verified by the screens below : 

![screenshot_20180329-215128](https://user-images.githubusercontent.com/10832531/38100762-e6db2eec-339b-11e8-8b70-16d45261635f.png)



![screenshot_20180329-215153](https://user-images.githubusercontent.com/10832531/38100765-e9cbc12a-339b-11e8-8d87-2d72e066f85a.png)
