### ISSUE TITLE
Nutrition Facts are not correctly displayed on all products

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2620]
![image](https://user-images.githubusercontent.com/1689815/57468633-27797980-7285-11e9-8eb8-07d501318dbb.png)
https://barcode.tec-it.com/en/EAN13?data=5400101047594

**Comment by stephanegigandet** [comment]
This is most likely because of an harmonization of the types in the JSON.

There are different fields in the nutriments hash, and some of them must not be used:

energy_100g: 1172,
energy: 1172,
energy_value: 280,
energy_unit: "kcal",
energy_serving: 1170,

energy_value and energy_unit are what the user entered, they may be per 100g or per serving.  energy is a conversion of energy_value to the default unit for the nutrient (here kJ). --> THOSE FIELDS ARE FOR INTERNAL USE AND SHOULD NOT BE USED. They are only used to display the product edit form. Note that the _unit field can be empty if not set by some apps.

energy_100g and energy_serving are the values that should be used. They are expressed in the default unit (kJ for energy, and grams for everything else).

**Comment by stephanegigandet** [comment]
numeric values are now always numeric (for some products they were strings before)

**Comment by deniger** [comment]
I checked that the values used are _100g and _serving -> ok

**Comment by deniger** [comment]
one thing to finish: to display nutriment value I use the unit entered by the user ( after conversion).
Normally we should use the taxonomy to choose the correct unit the taxonomy is not yet loaded in the App ( too complicate as far I understand)

**Comment by stephanegigandet** [comment]
The unit field seems to be empty on some products, ones that have been last edited by some apps like Yuka it seems, e.g. https://world.openfoodfacts.org/api/v0/product/8410509003624/boisson-vegetale-riz-quinoa-costa-eco
One thing I could try is to create a unit field with the default unit for those products, on the server side.

**Comment by deniger** [comment]
it should be fixed. I modified the view to dispay nothing if no serving size

![image](https://user-images.githubusercontent.com/47569605/57510833-fee69380-7307-11e9-9656-743a7eecea3f.png)
