### ISSUE TITLE
The home button does not work in offline edit

### ISSUE THREAD

**Issue by SIMSEUNGMIN** [openfoodfacts/openfoodfacts-androidapp#2977]
<img src="https://user-images.githubusercontent.com/33623099/71549402-00cca680-2a00-11ea-8da4-c262f0970c3c.png" width="40%">

In this screen, don't work home button.

**Comment by VaiTon** [comment]
Hi @SIMSEUNGMIN and thank you for reporting this issue!

Could you please provide us with
* Your phone Android version
* The app version (You can find it in Settings -> Apps ->OpenFoodFacts)

It would be very helpful for investingating the issue!

**Comment by LuGO0** [comment]
![Capture](https://user-images.githubusercontent.com/30355336/71559544-631bba80-2a85-11ea-9b0b-b432870dc9a0.PNG)

Something to do with the CommonBottomListener ,since after clicking on the home button it checks the current activity which in case of offline edit remains MainActivity just the fragment is swapped so the CommonBottomListener does nothing and breaks.
[please zoom in the pic]

**Comment by LuGO0** [comment]
In addition to offline edit fragment the home button also dosent work in the search by barcode fragment

**Comment by LuGO0** [comment]
I can work on this bug !!

**Comment by LuGO0** [comment]
@teolemon  please review this !!

**Comment by teolemon** [comment]
@VaiTon can you have a look ?
