### ISSUE TITLE
Use translations for ingredient analysis modal

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#3006]
![image](https://user-images.githubusercontent.com/1689815/73143346-46c96880-4099-11ea-9375-2d832af67e40.png)
![image](https://user-images.githubusercontent.com/1689815/73143348-4b8e1c80-4099-11ea-9fe9-0d6590c455d5.png)
![image](https://user-images.githubusercontent.com/1689815/73143350-4fba3a00-4099-11ea-868b-d9e382c632eb.png)
Use translations for ingredient analysis modal. We currently seems to be using slugs

**Comment by teolemon** [comment]
`from_palm_oil`

**Comment by teolemon** [comment]
it's a bit complex: the type must be fetched from https://ssl-api.openfoodfacts.org/files/app/ingredients-analysis.json and then found in
https://static.openfoodfacts.org/data/taxonomies/ingredients_analysis.json to get the translations

**Comment by teolemon** [comment]
@ripetrescu can you have a look, so that we can release on the Play Store as well in the next few days ?

**Comment by ripetrescu** [comment]
Investigating :)

**Comment by ripetrescu** [comment]
@teolemon so this is not so hard to change, but for the 1st screenshot it will be:
"Display **Palm oil content unknown**" status instead of "Display from_palm_oil status" which is more generic (indeed not translated). But as a user if you choose to not display "Palm oil content unknown" status you would expect to see the "Palm oil free" status for example. But the option is to hide/show all the palm oil related statuses.

If this is acceptable I can do the change, just let me know :) Thanks

**Comment by teolemon** [comment]
``` 
"en:palm-oil-free": {
		"type": "from_palm_oil",
		"icon" : "monkey_happy", 
		"color": "#00aa00"
	},
```
```
"en:palm-oil":{"name":{"en":"Palm oil","fr":"Huile de palme"},"show_ingredients":{"en":"from_palm_oil:yes"}}```

**Comment by ripetrescu** [comment]
@teolemon  created https://github.com/openfoodfacts/openfoodfacts-androidapp/pull/3009

**Comment by teolemon** [comment]
I'm closing this. Thank you again @ripetrescu
