### ISSUE TITLE
Launch intent with products barcode for editing

### ISSUE THREAD

**Issue by DanieliusAsm** [openfoodfacts/openfoodfacts-androidapp#3059]
So I have an Android app Foodless thats mainly focused on expiration dates. I was wondering if there is a feature that I could launch OpenFoodFacts app with an intent specifying the barcode so the users could use your app to add/edit the product. That would save me time not having to code all the registering and editing products. I could do this feature myself if it is okay with anyone in charge.

**Comment by VaiTon** [comment]
Off you go! :-)

**Comment by DanieliusAsm** [comment]
Actually I changed my mind about this. Its a bad user experience forcing users to download another app, register and then scan the barcode for the 2nd time and register/edit.

**Comment by teolemon** [comment]
@DanieliusAsm the best way is to integrate contribution directly from your own app, using the WRITE API

**Comment by khalyomede** [comment]
Hi, I am developping a web app centered around product bar code scanning. I had the same interrogation as DanieliusAsm.

I would like to not "remake the wheel", and let people that are willing to contribute to do it directly from the OpenFoodFact Android app.

My goal is to provide an URL users can click, which opens the Android app (and ideally redirects to the PlayStore on Desktop - this part is not very important for me at this moment).

I read Google documentation about URL intents, and it defines the URL as it (using Instagram as an example):

```javascript
// Javascript code 

const url = "intent://instagram.com/#Intent;scheme=https;package=com.instagram.android;end";
```

Do you know what is the "com" name of the OpenFoodFact Android app? So that I can run some test opening it from my web app.
