### ISSUE TITLE
Change default name of list for OBF, OPF, OPFF

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#3066]
The default name of list is "eaten products". Change that to "Product that I have" for OBF, OPF, OPFF

**Comment by epicadk** [comment]
Can I work on this?

**Comment by VaiTon** [comment]
@epicadk sure you can! I'm assigning you! 👍

**Comment by epicadk** [comment]
un assigning as this issue has already been solved

**Comment by VaiTon** [comment]
@epicadk what do you mean? How has this been solved?

**Comment by yukiisbored** [comment]
I just cloned the project (I'm on commit fa6fa4647e970ccb20d843553e025b57fbc954e6) and can confirm that the default is now "Product that I have". Unless I misunderstood what "Change default name of list" means, I think this issue is fixed.

![Screenshot_1606003704](https://user-images.githubusercontent.com/18437312/99890427-4a992d80-2c5f-11eb-8966-5c36ba8f1c3a.png)
