### ISSUE TITLE
Lists export does not seem to be working. 

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#3077]
Lists export does not seem to be working. A transient tooltip says lists is being exported. 

- [ ] No confirmation that the export has completed
- [ ] No notification to open the file (like in the list export feature)
- [ ] No way to share the file using the Android Share Sheet.
- [ ] Possibly a broken export.

**Comment by Telperion87** [comment]
I would really like to export the lists of products i'm currently working on, so that I can someway "translate" them into direct links and work on a pc (more convenient for some editing aspects).

As I can see with this acknowledged bug, it's currently impossible. Is there any workaround? is there any place where the lists are saved in any form?

Thanks
