### ISSUE TITLE
Impossible to delete categories

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#3332]
**Describe the bug**
Impossible to delete categories
**To Reproduce**
1. Go to 'Edit'
2. Delete categories
3. Click save
4. Categories are still around

**Comment by VaiTon** [comment]
Ok so after a bit of investigation I came up with this:

### The code problem

At the moment, we check if the field is empty and if it is, we skip sending updated value. 

This is **wrong** because if we have to delete all categories then the edit will be skipped.

https://github.com/openfoodfacts/openfoodfacts-androidapp/blob/d4806ce35ed513464d7146d5cdddace94c5edd95/app/src/main/java/openfoodfacts/github/scrachx/openfood/fragments/AddProductOverviewFragment.java#L773

**Comment by stephanegigandet** [comment]
add_categories --> adds categories to the existing categories (and it keeps existing categories)
categories -> replaces the existing categories with the values passed
