### ISSUE TITLE
You can't switch language from settings anymore

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#3437]
You can't switch language from settings anymore
- [x] Taxonomy (works)
- [x] Robotoff (works)
- [ ] UI (broken)

**Comment by VaiTon** [comment]
Could you check with new commits?

**Comment by mrudultora** [comment]
I even changed the language of my device (also from settings of openfoodfacts) , but then also the strings didn't changed. All the words were in english. Although, the data coming from server was in desired language.

**Comment by VaiTon** [comment]
There are a lot of incostincencies when using language. We use a lot `Locale.getDefault()` when we should be using the settings language.

**Comment by mrudultora** [comment]
@VaiTon @teolemon I have pulled all the latest changes. When I install the app from android studio the language is changing. The one already installed from the playstore doesn't updates the language. 
Had someone fixed this issue already ?
I am attaching the screenshots of both the cases.

![img2](https://user-images.githubusercontent.com/65870389/104448969-e3935780-55c3-11eb-8119-87d916eb6ecd.jpg)

![img1](https://user-images.githubusercontent.com/65870389/104448956-e130fd80-55c3-11eb-82fb-819d863b0846.jpg)

In the second image the language is changed. Please, clarify this doubt.

**Comment by mrudultora** [comment]
@teolemon @VaiTon Are we uploading app bundle on play console. If that's true, then this is the reason for language switching not working. Because, at the time of downloading play store will only download the language that is currently set in user's device. In this case, we have 2 options. 
• Either we disable the split on the basis of language in the gradle file, but this will increase the app size because the app supports too many languages.
• Secondly, we can use **Google Play Core Library** to download resources at runtime, if needed. Have a look at this [link.](https://developer.android.com/guide/playcore#lang_resources)

**Comment by teolemon** [comment]
It's not split related, since manually changing the language works fine

**Comment by mrudultora** [comment]
Hi @teolemon , let me explain you completely. I downloaded the app from Playstore and at that time my device language was English. So, the strings were in English. Now, I manually changed my device language to Hindi from phone settings. Then I opened the app and the strings were still in English even after manually changing it. This clearly shows that `strings.xml (hi)` was not at all downloaded.
I guess your default device language is french. So, I suggest you to change your device language from phone settings (not from app settings) to any unknown language (change it to German or hindi). You will clearly see the difference. I am just putting my point because I recently faced the similar issue. The app bundle does not serve all the languages.

**Comment by mrudultora** [comment]
Might be you are manually switching between french and English. Please try switching to other languages manually from phone settings and you will surely see the difference. I hope I am able to explain you my point :-)

**Comment by teolemon** [comment]
I switched to Italian, and it works perfectly. French as well know.
I believe it might have been fixed in #3540 
But I swear I could reproduce a couple of days ago 🤷

**Comment by mrudultora** [comment]
@teolemon  So, I am unable to understand that why I am getting a contradicting result. Would you please look at this screen recording.


https://user-images.githubusercontent.com/65870389/110247467-64524c80-7f92-11eb-8d42-ae314fd90393.mp4

I changed my device language to french but the app was still in english (tried everything to get the french language in the app) . Video is a bit long as my phone was lagging. 
**I downloaded the latest beta version of the app from google playstore** Also, the pull request related to #3540 is closed (not merged ). @sarah541 had fixed a NPE related issue on language change in #3556 . This is a different issue, as their is no npe here but then also language is not changing. 
_Sorry, for pinging you agaiin and again._
