### ISSUE TITLE
Update F-Droid version

### ISSUE THREAD

**Issue by Krusty27** [openfoodfacts/openfoodfacts-androidapp#3823]
Please keep the F-Droid version up to date, lots of people depend on that.

**Comment by teolemon** [comment]
Background: I've tried, and had had 5 failures for several reasons (I fixed screenshot metadata, we fixed some tests…). 
We still can't release now because develop is broken, and creating a build now would result in another F-Droid failure (and I'm not even sure it would be enough).

https://gitlab.com/fdroid/fdroiddata/-/commits/db0158523df6c124f94dc5c5c98191655bfc9df7/metadata/openfoodfacts.github.scrachx.openfood.yml

So we would need: 

- [ ] to fix the build
- [ ] find out the issue that prevented 3.6.3 from being successful 3 weeks ago

**Comment by teolemon** [comment]
@Krusty27 the build is fixed, and I've created an interim release for F-Droid: https://github.com/openfoodfacts/openfoodfacts-androidapp/releases/tag/3.6.6
fingers crossed🤞

**Comment by Krusty27** [comment]
Great! You're the best :tada:

**Comment by Lee-Carre** [comment]
Could v3.7 (at least, if not v3.8) also be made available to F-Droid. I frequently encounter many of the bugs which (according to the release notes) v3.7 fixed, while stuck using v3.6.8 (the last release for F-Droid). Including the annoying ones which prevent correct data-upload.

This prevents me from contributing (in Jersey; not many contributors, here, and only <100 products).

I realise that the Smooth app is the new hotness, but at-least leave a functional release of the traditional app in the meantime.

Thankyou.
