### ISSUE TITLE
Offer to type barcode if no barcode is detected after 30s

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#445]
- Offer to type barcode if no barcode is detected after 30s in the Scan View. 
- Also add an option to dismiss forever
- If this option is chosen, add a final info that you can always search by barcode.

**Comment by herau** [comment]
I think the user will not wait 30 seconds :-) 5s / 10s may be more realistic ?

**Comment by teolemon** [comment]
Yes :-)

**Comment by Shubham2320** [comment]
I will work in this.

**Comment by samagra14** [comment]
@Shubham2320 Are you still working on this ?

**Comment by Shubham2320** [comment]
@samagra14  Yes I'm working on this, I've queued some of my taken issues so it is taking time.
By the way, you can take this issue if you're not indulged in any other issue :).

**Comment by teolemon** [comment]
Please don't hoard issues.

**Comment by Shubham2320** [comment]
okay, @teolemon I'll make sure it in future :).
And I've thought an approach in which after 15 seconds a small overlay will come at the top of ActionBar or fragment which would contain a message to enter a barcode instead of scanning and on choosing that option user will be taken to FindProductFragment to enter the barcode.

Can I use this approach?

**Comment by samagra14** [comment]
@Shubham2320 What's your progress on this?

**Comment by samagra14** [comment]
I guess overlay on the ActionBar would not be such a nice idea. Try overlay on the screen.

**Comment by Shubham2320** [comment]
@samagra14 yeah I'm going to send a PR :).
