### ISSUE TITLE
Small darkmode error in the Contributions tab

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#4613]
### What
- Small darkmode error in the Contributions tab

### Screenshot
![image](https://user-images.githubusercontent.com/1689815/160239321-b1556cac-4eb3-4584-8b40-9c7906c92ba6.png)

**Comment by galemu2** [comment]
I found the bug.  The `TextView` has a text color value that set set to black, `android:textColor="@color/black"`.  Possible solutions, are remove the text color. This view will use materials color.  Define text color in `colors.xml` file in both `colors` and `colors-night` folder. Or. use `android:textAppearance` with custom *style* or one inherited from Android platform's default text appearance. 

Since the `attribute_group_item.xml` file uses the `textAttribute` inplace of `textColor`, I think the `textAttribute` solution, using *inherited* **style** from Android platform sounds appropriate.  `android:textAppearance="@android:style/TextAppearance.DeviceDefault"`

**Comment by VaiTon** [comment]
Fixed by https://github.com/openfoodfacts/openfoodfacts-androidapp/pull/4628
