### ISSUE TITLE
Barcode Scanner as library or module

### ISSUE THREAD

**Issue by ReIaxo** [openfoodfacts/openfoodfacts-androidapp#4854]
### What
Is it possible to separate the Barcode scanner to a library or module so that other apps can easy implement OFF product scanning?

### Why/User story
I think many projects which use the OFF database want a Barcode scanning feature.

For example: Projects which have Issues related to Barcode scanner:
[Privacy friendly foodtracker](https://github.com/SecUSo/privacy-friendly-food-tracker) [# 89](https://github.com/SecUSo/privacy-friendly-food-tracker/issues/89)

**Comment by VaiTon** [comment]
For scanning barcodes we use MLKit and ZXing. What do you mean with a "Barcode scanner library"?

**Comment by ReIaxo** [comment]
I mean a ready to use OFF scanner fragment/view, that one can call and getting product result back after scanning.
Or is it that easy that something like that is not needed? Sorry, I haven't looked at the implementation here.

**Comment by DanieliusAsm** [comment]
[CameraX since 1.2.0-beta01](https://developer.android.com/jetpack/androidx/releases/camera#1.2.0-beta01) has a new library called _camera-mlkit-vision_: 

_New library camera-mlkit-vision. Easily integrate CameraX with many MLKit features, including barcode scanning, face detection, text detection, etc. Please find the sample code [here](https://github.com/androidx/androidx/blob/androidx-main/camera/integration-tests/viewtestapp/src/main/java/androidx/camera/integration/view/MlKitFragment.kt)._

I havent tried it myself but the implementation looks to be even easier than what I use.

**Comment by VaiTon** [comment]
I don't think we have enough resources here to do that, so I'm closing this for now as not planned. Feel free to create a PR though if you want!
