### ISSUE TITLE
City shown as a slug

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#51]
You can get their actual names at 
http://world.openfoodfacts.org/cities.json

**Comment by herau** [comment]
what do you mean exactly ? the cities names from the product API doesn't the right cities names ?

**Comment by teolemon** [comment]
@herau They have hyphens and are not accentuated

**Comment by teolemon** [comment]
![screenshot_20161104-172310](https://cloud.githubusercontent.com/assets/1689815/20013493/9dd40e6e-a2b3-11e6-859b-a1403ab79888.png)
@herau : here's a screenshot

**Comment by herau** [comment]
ok but it's only data that the users filled for the product right ? I will see the API result to see if it's really the user data that we use for the display

**Comment by herau** [comment]
@teolemon the displayed data came from the `cities_tags` product field. (json api).

if you want the right display, we have to fetch the cities api and then find the right city name according to its id. (`chantonnay-vendee-france` with your sample). 

http://world.openfoodfacts.org/cities.json

we also can't split the value with `-` because cities/states/countries could contains this kind of characters.

**Comment by teolemon** [comment]
I was indeed thinking about the canonical city name but it will impact performance to fetch them all. @stephanegigandet : can we put the canonical name in individual facets ?

http://world.openfoodfacts.org/city/sable-sur-sarthe-sarthe-france.json

**Comment by teolemon** [comment]
https://github.com/openfoodfacts/openfoodfacts-server/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20city
