### ISSUE TITLE
Logo splash screen broken on tablets and some phones.

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#517]
Splash screen broken on tablets. The logo is distorted and takes the whole screen.

**Comment by teolemon** [comment]
![image](https://cloud.githubusercontent.com/assets/1689815/24075755/a56d354c-0c21-11e7-9a3d-cf408a5018df.png)

**Comment by teolemon** [comment]
This also affect some mobile phones.

**Comment by samagra14** [comment]
@teolemon, I guess the problem is that currently, the splash screen is implemented via a dedicated splash activity which is not an optimal way of implementing splash screens. Moreover setting up SharedPref and other functionalities in the splash activity is also suboptimal. The correct way of implementing splash screens as stated by Google can be found on the link below:-
https://android.jlelse.eu/launch-screen-in-android-the-right-way-aca7e8c31f52
I can work on the alternate implementation if all agree to go by this approach because the sole purpose of a splash screen is to provide responsiveness during a cold startup. If we implement a dedicated splash activity, then during a cold startup, there will be no responsiveness. Please provide me feedback as to what you think regarding the same.

**Comment by samagra14** [comment]
@ross-holloway94 @teolemon Your views here, please.

**Comment by samagra14** [comment]
@teolemon SHould I start working on this issue and implement this screen as explained in the above method?

**Comment by ross-holloway94** [comment]
@samagra14 Yes, go ahead. Sorry for the late reply.

**Comment by huzaifaiftikhar** [comment]
The splash screen is completely revamped and this must have been fixed. Could be reopened if issue still persists.
