### ISSUE TITLE
Gamify using Google Play Games (option)

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#62]
Creating badges for completing missions, that would show up in Google Play Games, and create a virality effect
http://fr.openfoodfacts.org/missions

**Comment by LuccoJ** [comment]
Would this require adding a dependency on Google Play Services? :(

**Comment by jalami** [comment]
If this did require Google Play services, I couldn't use it anymore.

**Comment by itchix** [comment]
Can I get this data in the api? We don't need Google Play Service, we can "make" our own ranking system

**Comment by teolemon** [comment]
@jalami @LuccoJ @itchix 
I think we can have our own gamification system where you can earn achievements and the likes.
The idea I'm bringing forward is: 
- for those who already use Google Play Games and opt-in, can we -in addition- propose to publish the achievements through it ? It would be a way to get other people to discover Open Food Facts.
- for those who so wish, being able to share it on social networks.
- for those who so wish, keep it to yourself.

**Comment by Ekt0s** [comment]
Maybe like social game, e.g. Clash of Clans / SimCity / Crossy Road / etc... 
Everytime you achieve something within the game, you earn some xp points, afterwards you can earn Google Play Games' xp points and compare with your friends.

**Comment by LuccoJ** [comment]
@teolemon Gamification in itself would be nice, and you could propose to publish achievements through Google Play Games, but _please please please_ don't just make it "opt-in" in the sense that you can refuse to; it needs to be "opt-in" in the sense that there should be a separate build path for compiling the app _without_ linking to / including Play Services.

Otherwise, it cannot be included in F-Droid anymore, and I certainly won't be able to use it anymore (since I don't even have Play Services installed, even if I wanted to get the app from another source).

**Comment by ArchangeGabriel** [comment]
They are some apps having different builds for F-Droid and the Google Play Store, like riot.im, so this is definitively possible just in case someone was wondering about it.
