### ISSUE TITLE
Progress icon misplaced

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#842]
The progress icon is misplaced when uploading offline products.
A nice improvement would be to indicate progress directly by turning the red cross icon on the product line into a progress indicator.

![image](https://user-images.githubusercontent.com/1689815/36437148-815202fa-1666-11e8-9ebd-2827737a789d.png)

**Comment by Shubham2320** [comment]
@teolemon I'm also thinking to replace listView by RecyclerView can I do that?

**Comment by Shubham2320** [comment]
I also want to confirm what are all parameters about any product which are necessary to upload it.
On analyzing the code I found out the following code:
```java
 if (isEmpty(product.getBarcode()) || isEmpty(product.getImgupload_front())
                        || isEmpty(product.getBrands()) || isEmpty(product.getWeight()) || isEmpty(product.getName())) {
                    imageIcon = R.drawable.ic_no_red_24dp;
                }
```
which shows that if any of `product.getBarcode()` , `product.getImgupload_front()` , `product.getBrands()` , `product.getWeight()` , `product.getName()` **is empty** than only the **red cross icon** will be shown otherwise there is also a **green right icon** which is shown. 

And while uploading the data online it only checks `product.getBarcode()` and  `product.getImgupload_front()` is not empty and if it is not then products get uploaded.

So I want to confirm that don't we need to check other parameters like brand, name etc is before uploading a product.
Also as mentioned in the issue that red icon should be replaced with progressBar while uploading products is it also the case with green tick icon.

**Comment by Shubham2320** [comment]
@teolemon please look into it :).

**Comment by teolemon** [comment]
@itchix Can I have your opinion ?

**Comment by SaumiaSinghal** [comment]
Hie @teolemon, I would like to work on this issue.

**Comment by teolemon** [comment]
You can go ahead. During a test, I couldn't see the spinner on latest trunk though.

**Comment by SaumiaSinghal** [comment]
Yes, exactly, me too. I will go through the code and will try to fix that.
