### ISSUE TITLE
Allergen detector doesn't work

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#871]
I tried adding Mozarella as an additive. 

-It doesn't work for a product in German (that is Mozarella, but contains Milch)
- It doesn't work for a mozarella product in French that contains Mozarella in ingredients.

My UX is in English.

We should disable it completely until it's reliable

**Comment by sowmya9029** [comment]
What should we disable do you mean the "Allergen alert" menu item? Are you referring to the below screen where Mozarella is shown in English when set to other language ?
![device-2018-02-23-115216](https://user-images.githubusercontent.com/11407233/36614125-89ef1db8-1890-11e8-881f-39c671e9a035.png)
 Can you given me more inputs so that I can start working on this.
